version: "2"
services:
        react-app:
                image: react
                command: yarn start
                volumes:
                        - ./myweb:/workspace
                ports:
                        - 3000:3000
                restart: always
